##############################
### WINDOWS AND WORKSPACES ###
##############################
# Float any window with "float" in class
windowrule = match:class .*float.*, float true

# Picture-in-Picture
windowrule = match:title ^Picture-in-Picture$, float true
windowrule = match:title ^Picture-in-Picture$, pin true
windowrule = match:title ^Picture-in-Picture$, size 50% 50%
windowrule = match:title ^Picture-in-Picture$, no_dim true

# Ignore maximize requests from apps
windowrule = match:class .*, suppress_event maximize
# Ignore transparency for browser
windowrule = match:class ^zen, opacity 1 1 1
