##############################
### WINDOWS AND WORKSPACES ###
##############################
# Float any window with "float" in class
windowrule = match:class .*float.*, float true

# Picture-in-Picture
windowrule {
  name = Picture-in-Picture
  match:title =  ^Picture-in-Picture$ 
  float =  true
  pin =  true
  size =  50% 50%
  no_dim = true
  opacity =  1 1
  keep_aspect_ratio = true
}
# Ignore maximize requests from apps
windowrule = match:class .*, suppress_event maximize

# Transparency for all windows
windowrule = match:class .*, opacity 0.9 0.9

# Keep some program opaque
# windowrule = match:class ^(zen)$, opacity 1 1
windowrule = match:class ^(mpv)$, opacity 1 1
windowrule = match:class ^(mpv)$, idle_inhibit true
# windowrule = match:class .*(firefox|chromium|brave|zen).*, opacity 1 1
