##############################
### WINDOWS AND WORKSPACES ###
##############################
# Float any window with "float" in class
windowrule = match:class .*float.*, float true

# Picture-in-Picture
windowrule = match:title ^Picture-in-Picture$, float true
windowrule = match:title ^Picture-in-Picture$, pin true
windowrule = match:title ^Picture-in-Picture$, size 50% 50%
windowrule = match:title ^Picture-in-Picture$, no_dim true
windowrule = match:title ^Picture-in-Picture$, opacity 1 1

# Ignore maximize requests from apps
windowrule = match:class .*, suppress_event maximize

# Transparency for all windows
windowrule = match:class .*, opacity 0.9 0.9

# Keep some program opaque
# windowrule = match:class ^(zen)$, opacity 1 1
windowrule = match:class ^(mpv)$, opacity 1 1
# windowrule = match:class .*(firefox|chromium|brave|zen).*, opacity 1 1
