-- Generated by hyprconf2lua v1.0.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'
hl.on("hyprland.start", function()
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("systemctl --user start hyprpolkitagent || lxpolkit || polkit-gnome-authentication-agent-1 || polkit-kde-authentication-agent-1")
end)
