-- Generated by hyprconf2lua v1.0.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- https://wiki.hyprland.org/Configuring/Variables/#general

hl.config({
    general = {
        gaps_in = 5,
        gaps_out = 10,
        border_size = 0,
        col = {
          active_border = 0xffffff00,
          inactive_border = 0xffffff33
        },
        resize_on_border = false,
        allow_tearing = false,
        layout = "dwindle",
    },
})
