-- Generated by hyprconf2lua v1.0.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives
---@module 'hl'
local mainMod = "SUPER"
local scripts = os.getenv("HOME") .. "/.config/hypr/scripts/master"

hl.bind(mainMod .. " + " .. "Q", hl.dsp.exec_cmd("kitty"))
hl.bind(mainMod .. " + " .. "C", hl.dsp.window.close())
hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd("local_var_fileManager"))
hl.bind(mainMod .. " + " .. "F", hl.dsp.window.float())
hl.bind(mainMod .. " + " .. "F", hl.dsp.window.pin())
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "F", hl.dsp.window.fullscreen())
hl.bind(mainMod .. " + " .. "R", hl.dsp.exec_cmd(scripts .. "/open_launcher.sh"))
hl.bind(mainMod .. " + " .. "V", hl.dsp.exec_cmd(scripts .. "/open_clipboard.sh"))

-- Submap: subsystem

hl.bind("ALT" .. " + " .. "S", hl.dsp.submap("system"))

hl.define_submap("system", function()
    hl.bind("B", hl.dsp.exec_cmd("ghostty --class=com.ghostty.float -e bluetui"))
    hl.bind("W", hl.dsp.exec_cmd("ghostty --class=com.ghostty.float -e sh -c wlctl || nmtui"))
    hl.bind("A", hl.dsp.exec_cmd("ghostty --class=com.ghostty.float -e pulsemixer"))
    hl.bind("M", hl.dsp.exec_cmd("ghostty --class=com.ghostty.float -e btop"))
    hl.bind("escape", hl.dsp.submap("reset"))
end)


-- Submap: power

hl.bind("ALT" .. " + " .. "P", hl.dsp.submap("power"))

hl.define_submap("power", function()
    hl.bind("S", hl.dsp.exec_cmd("poweroff"))
    hl.bind("R", hl.dsp.exec_cmd("reboot"))
    hl.bind("L", hl.dsp.exec_cmd(scripts .. "/lock_screen.sh"))
    hl.bind("H", hl.dsp.exec_cmd(scripts .. "/toggle_idle.sh"))
    hl.bind("M", hl.dsp.exec_cmd("hyprshutdown || hyprctl dispatch exit"))
    hl.bind("escape", hl.dsp.submap("reset"))
end)


-- Move focus with mainMod + vim keys
hl.bind(mainMod .. " + " .. "H", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + " .. "L", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + " .. "K", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + " .. "J", hl.dsp.focus({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]
hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))

-- Relative workspcae movement 

hl.bind(mainMod .. " + " .. "N", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mainMod .. " + " .. "P", hl.dsp.focus({ workspace = "e-1" }))

-- Example special workspace (scratchpad)

hl.bind(mainMod .. " + " .. "S", hl.dsp.workspace.toggle_special("magic"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "S", hl.dsp.window.move({ workspace = "special:magic" }))

hl.bind(mainMod .. " + " .. 0, hl.dsp.workspace.toggle_special("zero"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 0, hl.dsp.window.move({ workspace = "special:zero" }))

-- Scroll through existing workspaces with mainMod + scroll

hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging

hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true })

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true })

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })

hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true })

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl s 10%+"), { locked = true })

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl s 10%-"), { locked = true })

-- Requires playerctl

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })

hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

-- Custom

hl.bind(mainMod .. " + " .. "b", hl.dsp.exec_cmd(scripts .. "/toggle_bar.sh"))

-- HyprShot

hl.bind(mainMod .. " + " .. "Print", hl.dsp.exec_cmd("hyprshot -m window -o ~/Pictures/HyprShots"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "Print", hl.dsp.exec_cmd("hyprshot -m output -o ~/Pictures/HyprShots"))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "Print", hl.dsp.exec_cmd("hyprshot -m region -o ~/Pictures/HyprShots"))

-- media control with playerctl

hl.bind(mainMod .. " + " .. "Home", hl.dsp.exec_cmd("playerctl previous"))

hl.bind(mainMod .. " + " .. "Insert", hl.dsp.exec_cmd("playerctl --all-players play-pause"))

hl.bind(mainMod .. " + " .. "End", hl.dsp.exec_cmd("playerctl next"))

hl.bind(mainMod .. " + " .. "Delete", hl.dsp.exec_cmd("playerctl shuffle toggle && notify-send --transient --urgency=low Shuffle $(playerctl shuffle)"))
