-- Generated by hyprconf2lua v1.0.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.env("UI_ENV", "qs_noctalia")





hl.layer_rule({
    match = {
        namespace = "noctalia-background-.*$",
    },
    ignore_alpha = 0.5,
    blur = true,
    blur_popups = true,
})

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("noctalia-shell||qs -c noctalia-shell")
    hl.exec_cmd("pkill hyprpaper")
    hl.exec_cmd("pkill vicinae-server")
    hl.exec_cmd("pkill hypridle")
end)
