-- Generated by hyprconf2lua v1.0.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--#############################

--## WINDOWS AND WORKSPACES ###

--#############################

-- Float any window with "float" in class

hl.window_rule({
    name  = "match_class____float",
    match = {
        class = "float true",
    },
    -- TODO: review rule: "match:class . *float.*"
})

-- Picture-in-Picture

hl.window_rule({
    name  = "Picture-in-Picture",
    match = {
        title = "^Picture-in-Picture$",
    },
    float = true,
    pin = true,
    size = { "50%", "50%" },
    no_dim = true,
    opacity = "1.0",
    keep_aspect_ratio = true,
})

-- Ignore maximize requests from apps

hl.window_rule({
    name  = "match_class___",
    match = {
        class = "suppress_event maximize",
    },
    -- TODO: review rule: "match:class .*"
})

-- Transparency for all windows

-- windowrule = match:class .*, opacity 1 1

hl.window_rule({
    name  = "match_class___",
    match = {
        class = "opacity 0.9 0.9",
    },
    -- TODO: review rule: "match:class .*"
})

-- Keep some program opaque

hl.window_rule({
    name  = "match_class___mpv__",
    match = {
        class = "opacity 1 1",
    },
    -- TODO: review rule: "match:class ^(mpv)$"
})

hl.window_rule({
    name  = "match_class___mpv__",
    match = {
        class = "idle_inhibit true",
    },
    -- TODO: review rule: "match:class ^(mpv)$"
})

hl.window_rule({
    name  = "match_class_____fire",
    match = {
        class = "opacity 1 1",
    },
    -- TODO: review rule: "match:class . *(firefox|chromium|brave|zen).*"
})
