-- Generated by hyprconf2lua v1.0.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    xwayland = {
        force_zero_scaling = true,
    },
})

hl.env("GDK_SCALE", 1.25)

hl.env("XCURSOR_SIZE", 24)
