-- Generated by hyprconf2lua v1.0.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    wallpaper = {
        path = "~/Pictures/w2.jpg",
        fit_mode = "cover",
    },
})
-- NOTE: Section 'wallpaper' may be a plugin or custom section; verify the output

-- TODO: manual review: splash = true

-- TODO: manual review: ipc = false
