# Hyprland configuration
# Source all config files from hyprconf directory

source = ~/.config/hypr/hyprconf/monitors.conf
source = ~/.config/hypr/hyprconf/programs.conf
source = ~/.config/hypr/hyprconf/autostart.conf
source = ~/.config/hypr/hyprconf/env.conf
source = ~/.config/hypr/hyprconf/general.conf
source = ~/.config/hypr/hyprconf/decoration.conf
source = ~/.config/hypr/hyprconf/animations.conf
source = ~/.config/hypr/hyprconf/layout.conf
source = ~/.config/hypr/hyprconf/input.conf
source = ~/.config/hypr/hyprconf/keybinds.conf
source = ~/.config/hypr/hyprconf/rules.conf

source = ~/.config/hypr/hyprconf/qs_noctalia.conf
