-- Generated by hyprconf2lua v1.0.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives
-- Hyprland configuration
-- Source all lua config files from hyprconf directory

---@module 'hl'
require("hyprconf.general")
require("hyprconf.monitors")
require("hyprconf.env")
require("hyprconf.animations")
require("hyprconf.autostart")
require("hyprconf.decoration")
require("hyprconf.input")
require("hyprconf.keybinds")
require("hyprconf.layout")
require("hyprconf.programs")
require("hyprconf.rules")
require("hyprconf.xwayland")
require("hyprconf.qs_noctalia")
