[ids]

*

[main]

# Maps capslock to escape when pressed and control when held.
# capslock = overload(control, esc)
tab = overload(l_tab, tab)
# tap capslock -> esc
capslock = overload(capslock, esc)
# behave like ctrl when held
[capslock:C]
# [alt]

[l_tab]
h = left
j = down
k = up
l = right
enter = backspace
