unbind C-b
set -g prefix C-s

unbind r
bind r source-file $HOME/.config/tmux/tmux.conf

set -g base-index 1
setw -g pane-base-index 1

setw -g mouse on

# Vim keys
setw -g mode-keys vi
set -g status-style "fg=#1a1b26,bg=#7aa2f7"
# bind-key h  select-pane -L
# bind-key j  select-pane -U
# bind-key k  select-pane -D
# bind-key l  select-pane -R

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
# set -g @plugin 'christoomey/vim-tmux-navigator'

# Status bar
set -g @plugin "janoamaral/tokyo-night-tmux"
set -g @tokyo-night-tmux_theme night
set -g @tokyo-night-tmux_transparent 1
set -g @tokyo-night-tmux_window_id_style none
set -g @tokyo-night-tmux_pane_id_style hide
set -g @tokyo-night-tmux_zoom_id_style hide

# Open in cd
bind '"' split-window -v -c "#{pane_current_path}"
bind '%' split-window -h -c "#{pane_current_path}"
bind 'c' new-window -c "#{pane_current_path}"

if "test ! -d ~/.config/tmux/plugins/tpm" \
     "run 'git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm &&\
     ~/.config/tmux/plugins/tpm/scripts/install_plugins.sh'"

run '~/.config/tmux/plugins/tpm/tpm'
